### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lzylinl** [Laserzwei/CarrierCommander#1]
https://github.com/Laserzwei/CarrierCommander/blob/8b737f0fd4bc382100a6b73c7ca3dac7e87d8aaf/mods/CarrierCommander/scripts/entity/ai/aggressiveCommand.lua#L222

**Comment by Laserzwei** [comment]
Ah I love bug reports that don't have any text describing the bug, and are missing any kind of log. NOT!
The `and nil` is known by me though, I didn't commit the change yet
