### ISSUE TITLE
Project uses code and features for which credit is not given

### ISSUE THREAD

**Issue by Cwhizard** [Laserzwei/CarrierCommander#3]
The entire issue I have is the removal of my name from the credits.

If you want to use my code OR the features they added you must put my name back into the credits. It's not much to ask, I am not claiming I wrote the whole project. but it was a really shitty thing to do to remove my name. That is the entire issue.

In the future, please discuss issues on github, that is where the project is located and that is where I check. I am just as guilty as you are about that so I am not laying blame on either one of us for the miscommunication. Lets try to work together.

**Comment by Laserzwei** [comment]
> Lets try to work together

I'm sure we can get on a common nominator here and further 
The only reason why I removed you from the 

**Author List** 

was that the people on there did really big and important changes for/with the mod. 
Your work is and was always appreciated, I planned to put your Name in the changeLog as well as the post announcing the 0.16 update for CarrierCommand mod on the forum (where most of the publicity is).
If you want it within the code I will add appropriate comments in there. I could also add a supporters/cooperators/helpers (or any other name you think is fittitng) list in the config file, where the authors are listed. Just tell me what you think is fitting?

> In the future, please discuss issues on github

I haven't seen any issues other than the ones I layed out in the pull request.
Merging your branch into the main-project was actually the very last thing I did on the 19th Feb. --edit: and integrating your code the way I had it in mind with commit 7d13bd3 --edit end .And I had overlooked, that you added yourself on the authors list. Which I saw the next day and did the according commit we are discussing about now. -Having in the back of my mind to put you and your changes on the forums as described above

**Comment by Cwhizard** [comment]
Listing as a contributor in the code will be fine for now.  I do plan on adding additional code to the project as time permits.  I find that attributions within the code tend to stick with a project, while those outside the code tend to get lost and forgotten.

**Comment by Laserzwei** [comment]
The sorting code from Hammelpilaw in the complex mod overview is such an example. I will add yours to the next commit
