### ISSUE TITLE
Suggestion for changing the directory structure to play nice with Avorion

### ISSUE THREAD

**Issue by Cwhizard** [Laserzwei/CarrierCommander#4]
I suggest moving the scripts and config folders to the top level directly under the CarrierCommander folder, rather than have them some 3 folders deep under CarrierCommander/mods/CarrierCommander/....

This way when syncing, pushing, or pulling the project to/from the Avorion folder, the files appear where they are supposed to be, not buried.  This will also eliminate the need for the dummy folder. 

Just a suggestion.  I am already doing this on the Cwhizard branch, but I also preserve the main branches directory structure for now.

**Comment by Laserzwei** [comment]
Koonshi (the Avorion developer) confirmed that mods will be located in a /mods/ directory. It is very unlikely that mods will get the permission to read/modify files outside of that directory. Hence I would like to keep all files in their respective directory (mods/carriercommander/*)

**Comment by Laserzwei** [comment]
Due to the absensce of concrete information from the Avorion devs and no further discussion occuring, will this request be closed
