### ISSUE TITLE
Fighters attack Civil ships

### ISSUE THREAD

**Issue by Phasehand** [Laserzwei/CarrierCommander#5]
Not really sure what's going on, but occasionally I'll have my fighters set to Auto Assign while I work on my ship and while I'm not paying attention they will go and kill a civil ship from a faction that hates me. I checked repeatedly that I had it set so that they would not target/attack Civils.
Beta branch of the game.

**Comment by Laserzwei** [comment]
I assume you also use version 0.10?
What kind of civils exactly? Good-traders, eq-traders, ...?
Currently civil ships are detected using:
`civilShip:getValue("civil")`
If you could check such an ship, if it has this value set, you would be helping by a lot

**Comment by Phasehand** [comment]
How would I check the value set?
I generally don't notice that they are attacking it until the notification that I killed a civil, but it seems to be one of the trader/salesman ones that will jump into a random/empty system by itself, after you've been in it for awhile, and doesn't have an option to trade or anything.
